@InitSpool drop_utils_users
DEFINE LIB_USER=lib
DEFINE APP_USER=app

PROMPT Drop &LIB_USER and &APP_USER
DROP USER &LIB_USER CASCADE
/
DROP USER &APP_USER CASCADE
/
DROP PUBLIC SYNONYM L1_chr_arr
/
DROP PUBLIC SYNONYM L1_num_arr
/
DROP PUBLIC SYNONYM chr_int_rec
/
DROP PUBLIC SYNONYM chr_int_arr
/
DROP PUBLIC SYNONYM utils
/

PROMPT Drop directory input_dir
DROP DIRECTORY input_dir
/
PROMPT Revoke UTL_File and DBMS_Lock from PUBLIC
REVOKE EXECUTE ON UTL_File FROM PUBLIC
/
REVOKE EXECUTE ON DBMS_Lock FROM PUBLIC
/
@EndSpool